<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<!-- <meta name="viewport" content="initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no"> -->
	<meta name="apple-mobile-web-app-capable" content="yes"> 
	<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
	<script src="../js/common.js"></script>
	<script src="../js/flexible.js"></script>
	<script src="https://cdn.bootcss.com/jquery-animateNumber/0.0.14/jquery.animateNumber.min.js"></script>
	<script src="https://cdn.bootcss.com/iScroll/5.2.0/iscroll-infinite.min.js"></script>
	<!-- <link href="https://cdn.bootcss.com/aos/2.2.0/aos.css" rel="stylesheet"> -->
	<!-- <script src="https://cdn.bootcss.com/aos/2.2.0/aos.js"></script> -->
	<link href="https://cdn.bootcss.com/animate.css/3.5.2/animate.min.css" rel="stylesheet">
</head>
